apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort   # or LoadBalancer (cloud)
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
